group = "im.zoe.labs.flutter_notification_listener"
version = "1.0-SNAPSHOT"

apply plugin: "com.android.library"
apply plugin: "org.jetbrains.kotlin.android"

android {
    namespace = "im.zoe.labs.flutter_notification_listener"
    compileSdk = 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_17.toString()
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
    }

    defaultConfig {
        minSdk = 21
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib"
}
