plugins {
    id "com.android.library"
}

group = "im.zoe.labs.flutter_notification_listener"
version = "1.0-SNAPSHOT"

android {
    namespace = "im.zoe.labs.flutter_notification_listener"
    compileSdk = 36

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
    }

    defaultConfig {
        minSdk = 21
    }
}

kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_17
    }
}
